export type Category = 'All' | 'Utilities' | 'Point of Sale' | 'Engagement' | 'Gamification' | 'Security' | 'Analytics';

export interface Module {
  id: string;
  name: string;
  slug: string;           // e.g. @official/tactical-guestbook
  author: string;
  verified: boolean;
  category: Exclude<Category, 'All'>;
  description: string;
  longDescription: string;
  tags: string[];
  cpu: string;            // avg CPU time
  ram: string;            // avg RAM
  downloads: string;
  version: string;
  license: string;
  color: string;
  icon: string;
  screenshots: string[];   // we'll use terminal-output text blocks instead
  changelog: string;
}

export const MODULES: Module[] = [
  {
    id: '1',
    name: 'Tactical Guestbook',
    slug: '@official/tactical-guestbook',
    author: 'Q-OS Team',
    verified: true,
    category: 'Utilities',
    description: 'Collect guest aliases and check-in timestamps. Persists an indexed log in Sled with automatic counter increments.',
    longDescription: 'The canonical Q-OS starting point. Tactical Guestbook accepts a guest alias from the Micro-UI, writes a timestamped entry to the local Sled store, increments a persistent counter, and returns a stylized digital receipt with the guest\'s check-in number. Battle-tested across 200+ venue deployments.',
    tags: ['check-in', 'guestbook', 'beginner'],
    cpu: '1.2ms avg',
    ram: '4 MB',
    downloads: '18.4k',
    version: '2.3.1',
    license: 'MIT',
    color: '#00ff41',
    icon: '📋',
    screenshots: [],
    changelog: '2.3.1 — Fixed counter race on concurrent check-ins.\n2.3.0 — Added check-in number to receipt payload.',
  },
  {
    id: '2',
    name: 'Flash Sale Trigger',
    slug: '@official/flash-sale-trigger',
    author: 'Q-OS Team',
    verified: true,
    category: 'Point of Sale',
    description: 'Owner broadcasts a time-limited discount code. Module validates guest eligibility and applies a price modifier to the active cart state.',
    longDescription: 'Flash Sale Trigger integrates tightly with the Admin Override Console. When an owner fires a broadcast with level=OFFER, this module intercepts the event, writes a time-boxed discount token to state, and updates all active guest sessions instantly via CRDT sync. Supports percentage and flat-rate discounts.',
    tags: ['discount', 'sales', 'pos', 'broadcast'],
    cpu: '0.8ms avg',
    ram: '3 MB',
    downloads: '9.1k',
    version: '1.4.0',
    license: 'MIT',
    color: '#ff7a2f',
    icon: '⚡',
    screenshots: [],
    changelog: '1.4.0 — Multi-discount stacking support.\n1.3.0 — Time-boxed expiry for discount tokens.',
  },
  {
    id: '3',
    name: 'VIP Validator Pro',
    slug: '@official/vip-validator',
    author: 'Q-OS Team',
    verified: true,
    category: 'Security',
    description: 'Pre-load a list of cryptographic tokens into Sled. Validate VIP guest access on QR scan with sub-2ms latency — zero cloud round-trips.',
    longDescription: 'VIP Validator Pro accepts a batch of HMAC-SHA256 tokens from an event manager\'s CSV and pre-loads them into the Sled store before doors open. When a guest scans, the module validates their token against the local store, marks it as consumed (preventing replay), and grants or denies access with an animated Micro-UI response.',
    tags: ['events', 'vip', 'security', 'tokens', 'hmac'],
    cpu: '0.6ms avg',
    ram: '12 MB',
    downloads: '6.7k',
    version: '3.1.2',
    license: 'MIT',
    color: '#facc15',
    icon: '🎟️',
    screenshots: [],
    changelog: '3.1.2 — HMAC-SHA256 validation hardened.\n3.1.0 — Replay-attack prevention via consumed-token bitset.',
  },
  {
    id: '4',
    name: 'Loyalty Stamp Card',
    slug: '@community/loyalty-stamp',
    author: 'neon_barista',
    verified: false,
    category: 'Engagement',
    description: 'Digital stamp card. Guests earn a stamp on each visit. After 10 stamps, a free-item coupon is written to their guest state.',
    longDescription: 'A community favourite. Loyalty Stamp Card reads a persistent per-guest stamp count from Sled (keyed by alias hash), increments it on each scan, and triggers a reward at configurable thresholds. Rewards are written as redeemable coupon objects that the Point of Sale module can validate.',
    tags: ['loyalty', 'rewards', 'engagement', 'returning-guests'],
    cpu: '1.8ms avg',
    ram: '5 MB',
    downloads: '4.3k',
    version: '0.9.4',
    license: 'Apache-2.0',
    color: '#c792ea',
    icon: '💜',
    screenshots: [],
    changelog: '0.9.4 — Fixed stamp count reset on Sled compaction.\n0.9.0 — Configurable reward thresholds via state key.',
  },
  {
    id: '5',
    name: 'Table Racer',
    slug: '@community/table-racer',
    author: 'flux_devx',
    verified: false,
    category: 'Gamification',
    description: 'Speed-click minigame. Guests compete for the fastest tap time at their table. Live leaderboard rendered in the Micro-UI.',
    longDescription: 'Table Racer injects a micro-game into the guest session. Guests tap a neon button as fast as possible; their reaction time is written to a shared leaderboard state key. The Micro-UI displays the real-time ranking via WebSocket updates, driving engagement and dwell time. Perfect for bars and arcades.',
    tags: ['game', 'leaderboard', 'bar', 'engagement', 'fun'],
    cpu: '2.1ms avg',
    ram: '6 MB',
    downloads: '3.8k',
    version: '1.2.0',
    license: 'MIT',
    color: '#00d4ff',
    icon: '🏎️',
    screenshots: [],
    changelog: '1.2.0 — WebSocket leaderboard push added.\n1.0.0 — Initial release.',
  },
  {
    id: '6',
    name: 'Menu Architect',
    slug: '@official/menu-architect',
    author: 'Q-OS Team',
    verified: true,
    category: 'Point of Sale',
    description: 'Dynamic menu rendering from a structured Sled state object. Supports categories, modifiers, dietary flags, and real-time 86 (sold out) updates.',
    longDescription: 'Menu Architect reads a structured menu JSON object from the `menu:current` Sled key and renders it as a high-fidelity mobile-first UI in the Micro-UI. When an item is marked sold out via the Admin HUD (setting `menu:86:item_id`), all active guest sessions update within 50ms via CRDT broadcast.',
    tags: ['menu', 'food', 'pos', 'restaurant', 'ordering'],
    cpu: '3.4ms avg',
    ram: '18 MB',
    downloads: '12.2k',
    version: '4.0.1',
    license: 'MIT',
    color: '#00ff41',
    icon: '🍽️',
    screenshots: [],
    changelog: '4.0.1 — Dietary filter icons (vegan, GF, nut-free).\n4.0.0 — Full modifier and variant support.',
  },
  {
    id: '7',
    name: 'Session Heatmap',
    slug: '@official/session-heatmap',
    author: 'Q-OS Team',
    verified: true,
    category: 'Analytics',
    description: 'Aggregate interaction timestamps by table and hour. Exports a heatmap JSON for the Admin Dashboard to visualise peak traffic periods.',
    longDescription: 'Session Heatmap runs as a passive observer module — it intercepts every EXECUTION_RECEIPT telemetry event and aggregates interaction counts into a `heatmap:{date}:{table}:{hour}` key structure in Sled. The Admin Dashboard\'s Analytics panel consumes this data to render peak-traffic visualisations without any cloud BI tool.',
    tags: ['analytics', 'heatmap', 'business-intelligence', 'traffic'],
    cpu: '0.4ms avg',
    ram: '8 MB',
    downloads: '7.9k',
    version: '1.1.0',
    license: 'MIT',
    color: '#00d4ff',
    icon: '📊',
    screenshots: [],
    changelog: '1.1.0 — Per-hour granularity added.\n1.0.0 — Daily aggregation only.',
  },
  {
    id: '8',
    name: 'Spin the Wheel',
    slug: '@community/spin-wheel',
    author: 'arcade_labs',
    verified: false,
    category: 'Gamification',
    description: 'Animated prize wheel. Configurable prize weights stored in Sled. Generates a signed coupon code on win.',
    longDescription: 'Spin the Wheel renders a physics-based prize wheel in the Micro-UI using CSS animations. Prize outcomes and their weights are configured via the `wheel:config` Sled key from the Admin HUD. On a winning spin, the module generates a time-limited, SHA-256 signed coupon code and writes it to `coupons:{guest_alias}` for the POS to redeem.',
    tags: ['game', 'prize', 'coupon', 'gamification', 'engagement'],
    cpu: '1.6ms avg',
    ram: '7 MB',
    downloads: '2.4k',
    version: '0.7.1',
    license: 'MIT',
    color: '#ff7a2f',
    icon: '🎡',
    screenshots: [],
    changelog: '0.7.1 — Weighted probability fix.\n0.7.0 — Signed coupon generation.',
  },
  {
    id: '9',
    name: 'Inventory Pulse',
    slug: '@official/inventory-pulse',
    author: 'Q-OS Team',
    verified: true,
    category: 'Analytics',
    description: 'Real-time inventory tracking. Decrements stock on scan, triggers a low-stock broadcast when threshold is breached.',
    longDescription: 'Inventory Pulse maintains a SKU inventory in the `inv:{sku}` Sled namespace. Each guest interaction that selects an item decrements the corresponding stock counter atomically. When stock drops below a configurable threshold (default: 5 units), the module fires a SYSTEM_BROADCAST with level=WARNING, alerting staff via the Admin HUD in real time.',
    tags: ['inventory', 'stock', 'retail', 'broadcast', 'warehouse'],
    cpu: '0.9ms avg',
    ram: '10 MB',
    downloads: '5.6k',
    version: '2.0.0',
    license: 'MIT',
    color: '#00ff41',
    icon: '📦',
    screenshots: [],
    changelog: '2.0.0 — Atomic decrement using Sled compare-and-swap.\n1.x — Deprecated non-atomic counter.',
  },
  {
    id: '10',
    name: 'QR Bouncer',
    slug: '@community/qr-bouncer',
    author: 'nightlife_dev',
    verified: false,
    category: 'Security',
    description: 'Rate-limit QR scans per table per hour. Prevents abuse and bot scanning. Writes a temporary block flag to Sled on violation.',
    longDescription: 'QR Bouncer protects high-value modules from automated scanning. It maintains a per-table sliding-window counter in Sled and rejects interactions that exceed the configured rate limit (default: 30 scans/hour/table). Blocked guests see a friendly "Come back soon" Micro-UI. Block records expire automatically via Sled TTL.',
    tags: ['rate-limit', 'security', 'abuse-prevention', 'bouncer'],
    cpu: '0.3ms avg',
    ram: '2 MB',
    downloads: '1.9k',
    version: '1.0.3',
    license: 'MIT',
    color: '#ff003c',
    icon: '🚧',
    screenshots: [],
    changelog: '1.0.3 — Sliding window algorithm (was fixed window).\n1.0.0 — Initial release.',
  },
  {
    id: '11',
    name: 'Trivia Night Host',
    slug: '@community/trivia-night',
    author: 'pub_quiz_labs',
    verified: false,
    category: 'Gamification',
    description: 'Host a live trivia game across all tables simultaneously. Questions broadcast via WebSocket, answers collected in Sled, scores tallied in real-time.',
    longDescription: 'Trivia Night Host turns every table QR into a buzzer. The owner broadcasts a question from the Admin HUD; guests submit answers via the Micro-UI; the module tallies scores in `trivia:{round}:{alias}` state keys. A live leaderboard is streamed back to guests over WebSocket. Supports 2–200 simultaneous players.',
    tags: ['trivia', 'game', 'multiplayer', 'pub', 'leaderboard', 'events'],
    cpu: '4.2ms avg',
    ram: '22 MB',
    downloads: '3.1k',
    version: '2.1.0',
    license: 'Apache-2.0',
    color: '#facc15',
    icon: '🧠',
    screenshots: [],
    changelog: '2.1.0 — Live leaderboard via WebSocket push.\n2.0.0 — Multi-round support.',
  },
  {
    id: '12',
    name: 'Tip Jar',
    slug: '@community/tip-jar',
    author: 'barista_protocol',
    verified: false,
    category: 'Point of Sale',
    description: 'Digital tip jar. Guest selects a preset amount or enters custom. Aggregates tips per staff member per shift in Sled.',
    longDescription: 'Tip Jar provides a frictionless tipping flow directly in the guest\'s browser — no app, no payment processor required in the module itself (integrates with your existing Stripe terminal for charge processing). Tips are logged to `tips:{date}:{staff_id}` in Sled, giving shift managers an instant total without a POS report.',
    tags: ['tips', 'pos', 'payments', 'hospitality', 'staff'],
    cpu: '1.1ms avg',
    ram: '4 MB',
    downloads: '2.7k',
    version: '1.3.0',
    license: 'MIT',
    color: '#00ff41',
    icon: '💸',
    screenshots: [],
    changelog: '1.3.0 — Custom tip amount input.\n1.2.0 — Per-shift aggregation.',
  },
];

export const CATEGORIES: Category[] = ['All', 'Utilities', 'Point of Sale', 'Engagement', 'Gamification', 'Security', 'Analytics'];

export const CATEGORY_COLORS: Record<string, string> = {
  Utilities:    '#00ff41',
  'Point of Sale': '#ff7a2f',
  Engagement:   '#c792ea',
  Gamification: '#facc15',
  Security:     '#ff003c',
  Analytics:    '#00d4ff',
};
